/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HelpIndexImport } from './routes/help/index'
import { Route as HelpUsageImport } from './routes/help/usage'
import { Route as HelpSetsImport } from './routes/help/sets'
import { Route as HelpInstallationImport } from './routes/help/installation'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const HelpIndexRoute = HelpIndexImport.update({
  path: '/help/',
  getParentRoute: () => rootRoute,
} as any)

const HelpUsageRoute = HelpUsageImport.update({
  path: '/help/usage',
  getParentRoute: () => rootRoute,
} as any)

const HelpSetsRoute = HelpSetsImport.update({
  path: '/help/sets',
  getParentRoute: () => rootRoute,
} as any)

const HelpInstallationRoute = HelpInstallationImport.update({
  path: '/help/installation',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/help/installation': {
      preLoaderRoute: typeof HelpInstallationImport
      parentRoute: typeof rootRoute
    }
    '/help/sets': {
      preLoaderRoute: typeof HelpSetsImport
      parentRoute: typeof rootRoute
    }
    '/help/usage': {
      preLoaderRoute: typeof HelpUsageImport
      parentRoute: typeof rootRoute
    }
    '/help/': {
      preLoaderRoute: typeof HelpIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  HelpInstallationRoute,
  HelpSetsRoute,
  HelpUsageRoute,
  HelpIndexRoute,
])

/* prettier-ignore-end */
